@startuml
'https://plantuml.com/sequence-diagram

title US010 System Sequence Diagram

autonumber "<b>[00]"

actor Administrator

activate Administrator

Administrator -> ":System": asks to create a new employee
activate ":System"
Administrator <-- ":System": shows job role categories list and ask to select one
deactivate ":System"

Administrator -> ":System": selects a job role category
activate ":System"
Administrator <-- ":System": request data (name, phone number, email, address, citizen card id)
deactivate ":System"

Administrator -> ":System":  types requested data
activate ":System"
Administrator <-- ":System": presents all data and requests confirmation
deactivate ":System"

Administrator -> ":System": confirms the data
activate ":System"
Administrator <-- ":System": informs operation (In)success
deactivate ":System"

deactivate Administrator

@enduml