@startuml
'https://plantuml.com/class-diagram

left to right direction
skinparam classAttributeIconSize 0
hide methods

class ApplicationUser {
-name
-emailAddress
-role
-password
-address
-citizenCardNumber
}

class Employee {
-id
}

class Administrator

Administrator "*" -- "1" Application : manages >

class SnsUser {
-snsUserNumber
}

ApplicationUser <|-- Employee
ApplicationUser <|--- SnsUser
Employee <|-- Nurse
Employee <|-- Receptionist
Employee <|- Administrator
Employee <|-- CenterCoordinator



class Receptionist





class Nurse



class VaccinationCenter {
-intID
-strName
-strPhoneNumber
-strEmail
-strFax
-strWebsite
-strOpeningHour
-strClosingHour
-strSlotDuration
-strVaccinesPerSlot
-strRoad
-strZipCode
-strLocal
-strCenterCoordinatorID
 }

class MassVaccinationCenter extends VaccinationCenter {

}

class HealthcareCenter extends VaccinationCenter {
-ARE
-AGES
}

class Vaccine {
-brand
-name
-id
}

class AdministrationProcess {
-numberOfDoses
-dosage
-age
-intervalBetweenVaccines
}

class VaccineType {
-code
-description
-technology
}


Vaccine "1" -- "*" AdministrationProcess : has a >
VaccineType "*" -- "1" Vaccine :is of <

class DigitalCertificate


SnsUser "1" ---- "1" DigitalCertificate : requests >

class VaccineAppointment {
-date
}

SnsUser "1" --- "*" VaccineAppointment : schedules >




Receptionist "*" - "1" UsersWaitingList : atualizes >
Nurse "*" -- "1" UsersWaitingList : checks >
Nurse "1" - "*" Vaccine : administers >
VaccineAppointment "*" -- "1" VaccineType : is associated to a >
UsersWaitingList "1" --- "*" SnsUser: has >


class VaccineBulletin {


}



class AdverseReactions

VaccineBulletin "*" --- "1" AdverseReactions : can have an >

Nurse "1" -- "*" VaccineBulletin : records >
Nurse "1" -- "*" AdverseReactions : records >



class Application
class EntriesAndExitsList
Class VaccineBulletin {
-dateTimeOfLastDose
-doseNumber
-lotNumber
}

Application "1" --- "*" SnsUser : requests authorization to send SMS >
Application "1" --- "*" SnsUser : notify >
VaccinationCenter "1" -up- "*" EntriesAndExitsList : has >
Receptionist "1" -- "*" VaccineAppointment : schedules >

VaccinationCenter "1" -- "*" VaccineBulletin : has >

Application "1" -- "1" DailyTask: executes >
VaccineBulletin "*" -- "1" Vaccine : is associated to >

class CenterCoordinator
class UsersWaitingList
CenterCoordinator "1" -- "1" VaccinationCenter : is coordinated by <
VaccinationCenter "1" -u- "*" VaccineAppointment : has >
SnsUser "1" -- "*" VaccineBulletin: has >
CenterCoordinator "1" --> "*" VaccinationStatistics : checks and exports >
VaccinationStatistics "*" --> "1" VaccinationCenter : are related to >

class PerformanceAnalyzer

PerformanceAnalyzer "1" --> "1" VaccinationCenter : analyzes >

CenterCoordinator "1" --> "1" PerformanceAnalyzer : utilizes >

class Arrival {
-snsNumber
-arrivalTime
-vaccineType
}

class Departure {
-snsNumber
-departureTime
}

class PerformanceAnalyzer {
}

class InformationToAnalyze {
}

Arrival "*" -- "1" VaccineType : is associated to >

PerformanceAnalyzer "1" -- "1" InformationToAnalyze : has >

InformationToAnalyze "1" -- "1" VaccinationCenter : is related to >

InformationToAnalyze "1" -- "*" Arrival : utilizes >

InformationToAnalyze "1" -- "*" Departure : utilizes >

VaccinationCenter "1" -- "*" Arrival : has >

VaccinationCenter "1" -- "*" Departure : has >

CenterCoordinator "1" --> "*" LegacyData: imports
LegacyData "1" --> "1" VaccinationCenter: is related to
LegacyData "1" --> "*" SnsUser : has information on
LegacyData "1" --> "*" Arrival : has information on
LegacyData "1" --> "*" Departure : has information on
LegacyData "1" --> "*" Vaccine : has information on

@enduml